using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using StockFlow.Data;
using StockFlow.Filters;

namespace StockFlow.Controllers;

[SessionAuthorize]
public class InvoiceController : BaseController
{
    public InvoiceController(ApplicationDbContext context) : base(context) { }

    public async Task<IActionResult> Index() => View(await _context.Invoices.AsNoTracking().Include(i => i.Sale)
        .OrderByDescending(i => i.InvoiceDate).Take(250).ToListAsync());

    // Invoices are generated by the checkout flow so revenue and stock remain consistent.
    public IActionResult Create() => RedirectToAction("Create", "Sales");

    public async Task<IActionResult> Details(int id)
    {
        var invoice = await _context.Invoices.AsNoTracking().Include(i => i.Sale).FirstOrDefaultAsync(i => i.Id == id);
        return invoice is null ? NotFound() : View(invoice);
    }
}
