using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using StockFlow.Data;
using StockFlow.Filters;
using StockFlow.Helpers;

namespace StockFlow.Controllers;

[SessionAuthorize]
public class InvoiceController : BaseController
{
    public InvoiceController(ApplicationDbContext context) : base(context) { }

    public async Task<IActionResult> Index() => View(await _context.Invoices.AsNoTracking().Include(i => i.Sale)
        .OrderByDescending(i => i.InvoiceDate).Take(250).ToListAsync());

    // Invoices are generated by the checkout flow so revenue and stock remain consistent.
    public IActionResult Create() => RedirectToAction("Create", "Sales");

    public async Task<IActionResult> Details(int id)
    {
        var invoice = await _context.Invoices.AsNoTracking().Include(i => i.Sale).FirstOrDefaultAsync(i => i.Id == id);
        return invoice is null ? NotFound() : View(invoice);
    }

    // Approve a Pending invoice — marks it Paid. Admin only.
    [SessionAuthorize("Admin")]
    [HttpPost]
    public async Task<IActionResult> MarkPaid(int id)
    {
        var invoice = await _context.Invoices.FindAsync(id);
        if (invoice is null) return NotFound();

        if (invoice.PaymentStatus == "Pending")
        {
            invoice.PaymentStatus = "Paid";
            await _context.SaveChangesAsync();

            NotificationHelper.Add(_context, $"Invoice {invoice.InvoiceNumber} approved (marked Paid).", "Invoice", "Admin");
            await _context.SaveChangesAsync();

            TempData["Success"] = $"Invoice {invoice.InvoiceNumber} approved and marked as Paid.";
        }
        return RedirectToAction(nameof(Index));
    }
}
